### ISSUE TITLE
is there have corresponding papers?

### ISSUE THREAD

**Issue by v3551G** [zzklove3344/ApneaECGAnalysis#2]
is there have corresponding papers?
thanks.

**Comment by zzklove3344** [comment]
Yes, it has. However, paper is in Chinese. I will put it on GitHub later.

发件人: V3551G <notifications@github.com>
答复: zzklove3344/ApneaECGAnalysis <reply@reply.github.com>
日期: 2019年11月13日 星期三 下午3:46
收件人: zzklove3344/ApneaECGAnalysis <ApneaECGAnalysis@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zzklove3344/ApneaECGAnalysis] is there have corresponding papers? (#2)


is there have corresponding papers?
thanks.

**Comment by winnwi** [comment]
能分享相关的论文吗？

**Comment by Xixi-x-i** [comment]
请问可以分享相关论文吗

**Comment by zzklove3344** [comment]
有中文的论文，有需要的可以下载，
https://github.com/zzklove3344/ApneaECGAnalysis/MultiGFeatureInformationFusionLSTMGRNN DetectionforOSA.pdf

**Comment by zzklove3344** [comment]
有中文的已发表文献，已上传至项目根目录，MultiGFeatureInformationFusionLSTMGRNNDetectionforOSA.pdf

发件人: Xixi-x-i ***@***.***>
日期: 星期二, 2023年11月28日 10:52
收件人: zzklove3344/ApneaECGAnalysis ***@***.***>
抄送: zzklove3344 ***@***.***>, Comment ***@***.***>
主题: Re: [zzklove3344/ApneaECGAnalysis] is there have corresponding papers? (#2)

请问可以分享相关论文吗

―

**Comment by Xixi-x-i** [comment]
Thank you！



发自我的iPhone


------------------ Original ------------------
From: zzklove3344 ***@***.***&gt;
Date: Thu,Nov 30,2023 5:37 PM
To: zzklove3344/ApneaECGAnalysis ***@***.***&gt;
Cc: Xixi-x-i ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zzklove3344/ApneaECGAnalysis] is there have correspondingpapers? (#2)





 
Closed #2 as completed.
