### ISSUE TITLE
want to know the contents of the .npy file

### ISSUE THREAD

**Issue by raspatiocan** [zzklove3344/ApneaECGAnalysis#4]
Hi, @zzklove3344 
i want to know the contents of the file from
```
def get_dataset():
	train_rri_amp_edr = np.load("G:/python project/apneaECGCode/data/apnea-ecg_train_clear_rri_ramp_edr.npy")
	train_label = np.load("G:/python project/apneaECGCode/data/apnea-ecg_train_clear_label.npy")
	test_rri_amp_edr = np.load("G:/python project/apneaECGCode/data/apnea-ecg_test_clear_rri_ramp_edr.npy")
	test_label = np.load("G:/python project/apneaECGCode/data/apnea-ecg_test_clear_label.npy")
```
can you upload the file?

because I'm trying to use the GRU method and without using matlab.
thank you if you want to respond to me :)

**Comment by zzklove3344** [comment]
Files are too big, more than 20MB. So I upload those on Google Cloud, you can click [here](https://drive.google.com/drive/folders/1Qp2EEbB5NnCdhIcQY9rWyEbWJpXZv6GD?usp=sharing) to download.

**Comment by raspatiocan** [comment]
thank's for uploading those file:)
